### ISSUE TITLE
In the charts screen, when you pull down to refresh, onRefresh() will never be triggered

### ISSUE THREAD

**Issue by tenSunFree** [Sh4dowSoul/Compose-Scrobbler#59]
Because !refreshingState are always false, never trigger onRefresh().
Maybe you should removing !refreshingState.
<img width="596" alt="2021-04-29_202846" src="https://user-images.githubusercontent.com/23090085/116551245-4f5abf80-a92a-11eb-8801-c23c13677a6d.png">

**Comment by Sh4dowSoul** [comment]
Thanks for reporting the issue. It should already be fixed by #55 in the dev branch 👍
